<?php
$client_id = '129045643787467';
$client_secret = '9282bc94ab18e7abe2a15c074506171f';
$callback_url = "http://soneta.info/fb/return.php";
$perms = array ( 
				"publish_stream" ,
				"create_event" ,
				"rsvp_event",
				"sms",
				"offline_access",
				"email",
				"read_stream",
				"user_about_me",
				"friends_about_me",
				"user_activities",
				"friends_activities",
				"user_birthday",
				"friends_birthday",
				"user_education_history",
				"friends_education_history",
				"user_events",
				"friends_events",
				"user_groups",
				"friends_groups",
				"user_hometown",
				"friends_hometown",
				"user_interests",
				"friends_interests",
				"user_likes",
				"friends_likes",
				"user_location",
				"friends_location",
				"user_notes",
				"friends_notes",
				"user_online_presence",
				"friends_online_presence",
				"user_photo_video_tags",
				"friends_photo_video_tags",
				"user_photos",
				"friends_photos",
				"user_relationships",
				"friends_relationships",
				"user_religion_politics",
				"friends_religion_politics",
				"user_status",
				"friends_status",
				"user_videos",
				"friends_videos",
				"user_website",
				"friends_website",
				"user_work_history",
				"friends_work_history",
				"read_friendlists",
				"read_requests"				
				);
				
?>
